name: maternal_assistance_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0

  # UI & Icons
  lucide_flutter: ^0.548.0
  cupertino_icons: ^1.0.8

  # Functionality
  http: ^1.5.0
  flutter_local_notifications: ^17.2.1
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  flutter_markdown: ^0.7.3

  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env